<?php

namespace App\Services;

use App\Models\Application;
use Illuminate\Support\Str;
use Symfony\Component\Yaml\Yaml;

class SablierDynamicConfiguration
{
    public const GENERATED_FILENAME = 'sablier-apps.yml';

    public static function build(iterable $applications): ?string
    {
        $routers = [];
        $middlewares = [];
        $services = [];

        foreach ($applications as $application) {
            $definition = self::definitionForApplication($application);
            if ($definition === null) {
                continue;
            }

            $middlewares[$definition['middleware']] = [
                'plugin' => [
                    'sablier' => array_filter([
                        'group' => $definition['group'],
                        'sablierUrl' => $definition['sablier_url'],
                        'sessionDuration' => $definition['session_duration'],
                        'timeout' => $definition['timeout'],
                        'dynamic' => [
                            'displayName' => $definition['display_name'],
                        ],
                    ], fn ($value) => $value !== null),
                ],
            ];

            $services[$definition['service']] = [
                'loadBalancer' => [
                    'servers' => [
                        ['url' => "http://{$definition['alias']}:{$definition['port']}"],
                    ],
                ],
            ];

            foreach ($definition['domains'] as $index => $domain) {
                $router = [
                    'entryPoints' => [$domain['scheme'] === 'https' ? 'https' : 'http'],
                    'middlewares' => [$definition['middleware']],
                    'priority' => $definition['priority'],
                    'service' => $definition['service'],
                    'rule' => "Host(`{$domain['host']}`)",
                ];

                if ($domain['scheme'] === 'https') {
                    $router['tls'] = ['certResolver' => 'letsencrypt'];
                }

                $routers[$definition['router_prefix'].'-'.$index] = $router;
            }
        }

        if ($routers === []) {
            return null;
        }

        ksort($routers);
        ksort($middlewares);
        ksort($services);

        $configuration = [
            'http' => [
                'routers' => $routers,
                'middlewares' => $middlewares,
                'services' => $services,
            ],
        ];

        return "# This file is generated by Coolify. Do not edit it manually.\n".Yaml::dump($configuration, 12, 2);
    }

    private static function definitionForApplication(Application|array $application): ?array
    {
        $labels = self::labels($application);
        if (str($labels['sablier.enable'] ?? 'false')->lower()->value() !== 'true') {
            return null;
        }

        $group = self::slug($labels['sablier.group'] ?? self::value($application, 'name'));
        $alias = self::slug($labels['sablier.alias'] ?? "{$group}-sablier");
        $domains = self::domains(self::value($application, 'fqdn'));
        $port = self::port(self::value($application, 'ports_exposes'));

        if ($group === '' || $alias === '' || $domains === [] || $port === null) {
            return null;
        }

        return [
            'group' => $group,
            'alias' => $alias,
            'domains' => $domains,
            'port' => $port,
            'middleware' => 'sablier-'.$group,
            'router_prefix' => 'sablier-'.$group,
            'service' => 'sablier-'.$group,
            'priority' => (int) ($labels['sablier.priority'] ?? 10000),
            'sablier_url' => $labels['sablier.url'] ?? 'http://sablier:10000',
            'session_duration' => $labels['sablier.session_duration'] ?? '10m',
            'timeout' => $labels['sablier.timeout'] ?? '60s',
            'display_name' => self::value($application, 'name') ?: $group,
        ];
    }

    private static function labels(Application|array $application): array
    {
        $customLabels = self::value($application, 'custom_labels');
        if (blank($customLabels)) {
            return [];
        }

        $decoded = base64_decode($customLabels, true);
        $lines = preg_split('/\r\n|\r|\n/', $decoded === false ? $customLabels : $decoded) ?: [];

        return collect($lines)
            ->filter(fn ($line) => str($line)->contains('='))
            ->mapWithKeys(function ($line) {
                [$key, $value] = explode('=', $line, 2);

                return [trim($key) => trim($value)];
            })
            ->all();
    }

    private static function domains(?string $fqdn): array
    {
        if (blank($fqdn)) {
            return [];
        }

        return collect(explode(',', $fqdn))
            ->map(fn ($domain) => trim($domain))
            ->filter()
            ->map(function ($domain) {
                $url = parse_url(str_contains($domain, '://') ? $domain : 'https://'.$domain);
                $host = $url['host'] ?? null;
                if (blank($host)) {
                    return null;
                }

                return [
                    'host' => $host,
                    'scheme' => ($url['scheme'] ?? 'https') === 'http' ? 'http' : 'https',
                ];
            })
            ->filter()
            ->unique(fn ($domain) => $domain['scheme'].'://'.$domain['host'])
            ->values()
            ->all();
    }

    private static function port(?string $ports): ?int
    {
        $port = collect(explode(',', (string) $ports))
            ->map(fn ($port) => trim($port))
            ->filter()
            ->first();

        return is_numeric($port) ? (int) $port : null;
    }

    private static function slug(?string $value): string
    {
        return Str::of($value ?? '')->slug()->value();
    }

    private static function value(Application|array $application, string $key): mixed
    {
        return is_array($application) ? ($application[$key] ?? null) : data_get($application, $key);
    }
}
